base_url = "https://scott.stevenson.io"
title = "Scott Stevenson"
description = "Scott Stevenson’s website"
generate_feed = true
compile_sass = true
build_search_index = false

[markdown]
smart_punctuation = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
   { theme = "ir-white", filename = "syntax-light.css" },
   { theme = "visual-studio-dark", filename = "syntax-dark.css" },
 ]
