base_url = "https://scott.stevenson.io"
title = "Scott Stevenson"
description = "Scott Stevenson’s website"
generate_feed = true
compile_sass = true
build_search_index = false

[markdown]
highlight_code = false
smart_punctuation = true
