[build]
publish = "public/"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = "default-src 'none'; img-src 'self'; style-src 'self' 'unsafe-inline'"
Referrer-Policy = "no-referrer"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"

[[redirects]]
from = "https://scott-stevenson-io.netlify.app/*"
to = "https://scott.stevenson.io/:splat"
force = true

[[redirects]]
from = "https://stevenson.io/*"
to = "https://scott.stevenson.io/:splat"
force = true

[[redirects]]
from = "https://www.stevenson.io/*"
to = "https://scott.stevenson.io/:splat"
force = true

[[redirects]]
from = "/posts"
to = "/"
force = true
